// Package ai provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package aiapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for HazardTextResponseUrgency.
const (
	HIGH   HazardTextResponseUrgency = "HIGH"
	LOW    HazardTextResponseUrgency = "LOW"
	MEDIUM HazardTextResponseUrgency = "MEDIUM"
)

// Defines values for PresenceUpdateRequestStatus.
const (
	CAUTION PresenceUpdateRequestStatus = "CAUTION"
	DANGER  PresenceUpdateRequestStatus = "DANGER"
	SAFE    PresenceUpdateRequestStatus = "SAFE"
	UNKNOWN PresenceUpdateRequestStatus = "UNKNOWN"
)

// HazardTextRequest defines model for HazardTextRequest.
type HazardTextRequest struct {
	Text string `json:"text"`
}

// HazardTextResponse defines model for HazardTextResponse.
type HazardTextResponse struct {
	Confidence   float32                   `json:"confidence"`
	IncidentType string                    `json:"incident_type"`
	Urgency      HazardTextResponseUrgency `json:"urgency"`
}

// HazardTextResponseUrgency defines model for HazardTextResponse.Urgency.
type HazardTextResponseUrgency string

// PresenceUpdateRequest defines model for PresenceUpdateRequest.
type PresenceUpdateRequest struct {
	AccuracyM *float32                     `json:"accuracy_m"`
	Lat       float32                      `json:"lat"`
	Lon       float32                      `json:"lon"`
	Status    *PresenceUpdateRequestStatus `json:"status,omitempty"`
}

// PresenceUpdateRequestStatus defines model for PresenceUpdateRequest.Status.
type PresenceUpdateRequestStatus string

// PresenceUpdateResponse defines model for PresenceUpdateResponse.
type PresenceUpdateResponse struct {
	DisplayUntil time.Time `json:"display_until"`
	Ok           bool      `json:"ok"`
}

// SosRaiseRequest defines model for SosRaiseRequest.
type SosRaiseRequest struct {
	AlertBody string  `json:"alert_body"`
	Lat       float32 `json:"lat"`
	Lon       float32 `json:"lon"`
	RadiusM   int     `json:"radius_m"`
	TtlMin    int     `json:"ttl_min"`
}

// SosRaiseResponse defines model for SosRaiseResponse.
type SosRaiseResponse struct {
	Center    []float32 `json:"center"`
	ExpiresAt time.Time `json:"expires_at"`
	Ok        bool      `json:"ok"`
	RadiusM   int       `json:"radius_m"`
	SosId     string    `json:"sos_id"`
}

// PostClassifyHazardTextJSONRequestBody defines body for PostClassifyHazardText for application/json ContentType.
type PostClassifyHazardTextJSONRequestBody = HazardTextRequest

// PostPresenceUpdateJSONRequestBody defines body for PostPresenceUpdate for application/json ContentType.
type PostPresenceUpdateJSONRequestBody = PresenceUpdateRequest

// PostSosRaiseJSONRequestBody defines body for PostSosRaise for application/json ContentType.
type PostSosRaiseJSONRequestBody = SosRaiseRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostClassifyHazardTextWithBody request with any body
	PostClassifyHazardTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostClassifyHazardText(ctx context.Context, body PostClassifyHazardTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPresenceUpdateWithBody request with any body
	PostPresenceUpdateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPresenceUpdate(ctx context.Context, body PostPresenceUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSosRaiseWithBody request with any body
	PostSosRaiseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSosRaise(ctx context.Context, body PostSosRaiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostClassifyHazardTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClassifyHazardTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostClassifyHazardText(ctx context.Context, body PostClassifyHazardTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClassifyHazardTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPresenceUpdateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPresenceUpdateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPresenceUpdate(ctx context.Context, body PostPresenceUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPresenceUpdateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSosRaiseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSosRaiseRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSosRaise(ctx context.Context, body PostSosRaiseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSosRaiseRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostClassifyHazardTextRequest calls the generic PostClassifyHazardText builder with application/json body
func NewPostClassifyHazardTextRequest(server string, body PostClassifyHazardTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostClassifyHazardTextRequestWithBody(server, "application/json", bodyReader)
}

// NewPostClassifyHazardTextRequestWithBody generates requests for PostClassifyHazardText with any type of body
func NewPostClassifyHazardTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/classify/hazard-text")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostPresenceUpdateRequest calls the generic PostPresenceUpdate builder with application/json body
func NewPostPresenceUpdateRequest(server string, body PostPresenceUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPresenceUpdateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPresenceUpdateRequestWithBody generates requests for PostPresenceUpdate with any type of body
func NewPostPresenceUpdateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/presence/update")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSosRaiseRequest calls the generic PostSosRaise builder with application/json body
func NewPostSosRaiseRequest(server string, body PostSosRaiseJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSosRaiseRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSosRaiseRequestWithBody generates requests for PostSosRaise with any type of body
func NewPostSosRaiseRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sos/raise")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostClassifyHazardTextWithBodyWithResponse request with any body
	PostClassifyHazardTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClassifyHazardTextResponse, error)

	PostClassifyHazardTextWithResponse(ctx context.Context, body PostClassifyHazardTextJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClassifyHazardTextResponse, error)

	// PostPresenceUpdateWithBodyWithResponse request with any body
	PostPresenceUpdateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPresenceUpdateResponse, error)

	PostPresenceUpdateWithResponse(ctx context.Context, body PostPresenceUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPresenceUpdateResponse, error)

	// PostSosRaiseWithBodyWithResponse request with any body
	PostSosRaiseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSosRaiseResponse, error)

	PostSosRaiseWithResponse(ctx context.Context, body PostSosRaiseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSosRaiseResponse, error)
}

type PostClassifyHazardTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HazardTextResponse
}

// Status returns HTTPResponse.Status
func (r PostClassifyHazardTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostClassifyHazardTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPresenceUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PresenceUpdateResponse
}

// Status returns HTTPResponse.Status
func (r PostPresenceUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPresenceUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSosRaiseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SosRaiseResponse
}

// Status returns HTTPResponse.Status
func (r PostSosRaiseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSosRaiseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostClassifyHazardTextWithBodyWithResponse request with arbitrary body returning *PostClassifyHazardTextResponse
func (c *ClientWithResponses) PostClassifyHazardTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClassifyHazardTextResponse, error) {
	rsp, err := c.PostClassifyHazardTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClassifyHazardTextResponse(rsp)
}

func (c *ClientWithResponses) PostClassifyHazardTextWithResponse(ctx context.Context, body PostClassifyHazardTextJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClassifyHazardTextResponse, error) {
	rsp, err := c.PostClassifyHazardText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClassifyHazardTextResponse(rsp)
}

// PostPresenceUpdateWithBodyWithResponse request with arbitrary body returning *PostPresenceUpdateResponse
func (c *ClientWithResponses) PostPresenceUpdateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPresenceUpdateResponse, error) {
	rsp, err := c.PostPresenceUpdateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPresenceUpdateResponse(rsp)
}

func (c *ClientWithResponses) PostPresenceUpdateWithResponse(ctx context.Context, body PostPresenceUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPresenceUpdateResponse, error) {
	rsp, err := c.PostPresenceUpdate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPresenceUpdateResponse(rsp)
}

// PostSosRaiseWithBodyWithResponse request with arbitrary body returning *PostSosRaiseResponse
func (c *ClientWithResponses) PostSosRaiseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSosRaiseResponse, error) {
	rsp, err := c.PostSosRaiseWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSosRaiseResponse(rsp)
}

func (c *ClientWithResponses) PostSosRaiseWithResponse(ctx context.Context, body PostSosRaiseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSosRaiseResponse, error) {
	rsp, err := c.PostSosRaise(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSosRaiseResponse(rsp)
}

// ParsePostClassifyHazardTextResponse parses an HTTP response from a PostClassifyHazardTextWithResponse call
func ParsePostClassifyHazardTextResponse(rsp *http.Response) (*PostClassifyHazardTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostClassifyHazardTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HazardTextResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostPresenceUpdateResponse parses an HTTP response from a PostPresenceUpdateWithResponse call
func ParsePostPresenceUpdateResponse(rsp *http.Response) (*PostPresenceUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPresenceUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PresenceUpdateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSosRaiseResponse parses an HTTP response from a PostSosRaiseWithResponse call
func ParsePostSosRaiseResponse(rsp *http.Response) (*PostSosRaiseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSosRaiseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SosRaiseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
