package ai

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"time"

	aiclient "github.com/Storm-Watch-Platform/Storm_Watch_Backend/internal/aiapi" // generated by oapi-codegen
)

type Client struct {
	c *aiclient.ClientWithResponses
}

func New() (*Client, error) {
	base := os.Getenv("AI_SERVICE_BASE_URL")
	if base == "" {
		base = "http://localhost:8001"
	}
	httpc := &http.Client{Timeout: 30 * time.Second}
	c, err := aiclient.NewClientWithResponses(base, aiclient.WithHTTPClient(httpc))
	if err != nil {
		return nil, err
	}
	return &Client{c: c}, nil
}

func (cli *Client) ClassifyHazardText(ctx context.Context, text string) (urg, itype string, conf float64, err error) {

	req := aiclient.PostClassifyHazardTextJSONRequestBody{Text: text}
	resp, err := cli.c.PostClassifyHazardTextWithResponse(ctx, req)
	if err != nil {
		return "", "", 0, err
	}

	if resp.JSON200 == nil {
		return "", "", 0, fmt.Errorf("ai-service bad response: %d", resp.StatusCode())
	}

	return string(resp.JSON200.Urgency), resp.JSON200.IncidentType, float64(resp.JSON200.Confidence), nil
}

func (cli *Client) PresenceUpdate(ctx context.Context, lat, lon, acc *float64, status string) (displayUntil string, err error) {
	// tạo biến acc32 kiểu *float32
	var acc32 *float32
	if acc != nil {
		tmp := float32(*acc) // convert float64 -> float32
		acc32 = &tmp
	}

	body := aiclient.PostPresenceUpdateJSONRequestBody{
		Lat:       float32(*lat),
		Lon:       float32(*lon),
		AccuracyM: acc32,
		Status:    (*aiclient.PresenceUpdateRequestStatus)(&status),
	}

	resp, err := cli.c.PostPresenceUpdateWithResponse(ctx, body)
	if err != nil {
		return "", err
	}
	if resp.JSON200 == nil {
		return "", fmt.Errorf("ai-service bad response: %d", resp.StatusCode())
	}
	return resp.JSON200.DisplayUntil.Format(time.RFC3339), nil
}

func (cli *Client) SosRaise(ctx context.Context, body aiclient.PostSosRaiseJSONRequestBody) (*aiclient.SosRaiseResponse, error) {
	resp, err := cli.c.PostSosRaiseWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, fmt.Errorf("ai-service bad response: %d", resp.StatusCode())
	}
	return resp.JSON200, nil
}
